colors: true

commit-msg:
  jobs:
    - name: commitlint
      run: pnpm commitlint --edit {1}

pre-commit:
  parallel: true

  jobs:
    - name: format
      run: pnpm format && git add {staged_files}

    - name: lint
      run: pnpm lint

    - name: typecheck
      run: pnpm typecheck

pre-push:
  parallel: true

  jobs:
    - name: test
      run: pnpm test

#    - name: packages-audit
#      run: pnpm audit
