colors: true

prepare-commit-msg:
  commands:
    commitlint:
      run: pnpm commitlint --edit $1

pre-commit:
  parallel: false
  commands:
    format:
      run: pnpm format {staged_files} && git update-index --again
    lint:
      run: pnpm lint {staged_files}
    test:
      run: pnpm test:ci {staged_files}
    typecheck:
      run: pnpm typecheck

pre-push:
  parallel: true
  commands:
    typescript:
      run: pnpm typecheck
#    packages-audit:
#      tags: frontend security
#      run: pnpm audit
