colors: true

prepare-commit-msg:
  commands:
    commitlint:
      run: yarn commitlint --edit $1

pre-commit:
  parallel: true
  commands:
    biome:
      glob: "src/**/*"
      run: yarn biome:ci {staged_files} && git update-index --again
    test:
      run: yarn test:ci {staged_files}
    typecheck:
      run: yarn typecheck

pre-push:
  parallel: true
  commands:
    typescript:
      run: yarn typecheck
#    packages-audit:
#      tags: frontend security
#      run: yarn audit
